const data = [
  {
    "id":1,
    "title": "The silent patient",
    "author": "Alex Michaelides",
    "date_published": "February 5th 2019",
    "number_of_pages": 323,
    "type_of_book":"Thriller",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1550161053l/40097951._SY475_.jpg",
  },
  {
    "id":2,
    "title": "Playing with Demons",
    "author": "Cally Edwards",
    "date_published": "January 6th 2019",
    "number_of_pages": 291,
    "type_of_book":"Fantasy",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546902870l/43501985._SY475_.jpg",
  },
  {
    "id":3,
    "title": "The Tipping Point: How Little Things Can Make a Big Difference",
    "author": "Malcolm Gladwell",
    "date_published": "January 7th 2002",
    "number_of_pages": 301,
    "type_of_book":"Nonfiction, Business",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1473396980l/2612._SY475_.jpg",
  },
  {
    "id":4,
    "title": "The Power of Habit: Why We Do What We Do in Life and Business",
    "author": "Charles Duhigg",
    "date_published": "February 28th 2012 ",
    "number_of_pages": 375,
    "type_of_book":"Nonfiction, Psychology",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1545854312l/12609433._SY475_.jpg",
  },
  {
    "id":5,
    "title": "Indonesia, Etc: Exploring the Improbable Nation",
    "author": "Elizabeth Pisani",
    "date_published": "June 22nd 2015",
    "number_of_pages": 416,
    "type_of_book":"History",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1413749908l/23316545.jpg",
  },
  {
    "id":6,
    "title": "The Kiss Quotient",
    "author": "Helen Hoang",
    "date_published": "June 5th 2018",
    "number_of_pages": 336,
    "type_of_book":"Romance",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1527983720l/36577586._SY475_.jpg"
  },
  {
    "id":7,
    "title": "Elevation",
    "author": "Stephen King",
    "date_published": "October 30th 2018",
    "number_of_pages": 146,
    "type_of_book":"Fiction, Horror",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1542040067l/38355410._SX318_.jpg",
  },
  {
    "id":8,
    "title": "The Burning Maze",
    "author": "Rick Riordan",
    "date_published": "May 1st 2018",
    "number_of_pages": 431,
    "type_of_book":"Fantasy",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1516363168l/28006096.jpg",
  },
  {
    "id":9,
    "title": "The Outsider",
    "author": "Stephen King",
    "date_published": "May 22nd 2018",
    "number_of_pages": 561,
    "type_of_book":"Horror",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1524596540l/36124936._SY475_.jpg",
  },
  {
    "id":10,
    "title": "How Not to Be Wrong: The Power of Mathematical Thinking",
    "author": "Jordan Ellenberg",
    "date_published": "May 29th 2014",
    "number_of_pages": 480,
    "type_of_book":"Nonfiction, Science",
    "image_url":"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387726285l/18693884.jpg",
  },
]

export default data